### ISSUE TITLE
np.bool deprecated in numpy 1.20

### ISSUE THREAD

**Issue by danshapero** [inducer/compyte#32]
I'm getting a deprecation warning from [this line](https://github.com/inducer/compyte/blob/7533db88124045924a47d7392eaf9a078670fc4d/dtypes.py#L184) with numpy-1.20 saying that `np.bool` is just an alias for the builtin bool type. Is changing this likely to break or cause some awful performance regression on older numpy versions?

**Comment by inducer** [comment]
Thanks for the report! As you can probably tell from the surrounding code, the intention is for these types to all be sized, and `np.bool` isn't (just like `np.int` isn't, technically). I think `np.bool8` would be the correct replacement. (https://numpy.org/doc/stable/reference/arrays.scalars.html?highlight=bool_#numpy.bool8) #33 makes that change, https://github.com/inducer/loopy/pull/236 pulls it into loopy, https://github.com/inducer/pyopencl/pull/434 pulls it into pyopencl, https://gitlab.tiker.net/inducer/pycuda/-/merge_requests/43 pulls it into pycuda.

**Comment by inducer** [comment]
FWIW, I've verified that `np.bool8` is available back to at least Numpy 1.18.5.

**Comment by danshapero** [comment]
Ah that makes perfect sense, thanks so much Andreas!
